<?php

use Illuminate\Database\Seeder;
use App\CvMunicipality;

class CvMunicipalityTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $city = [
            ['name' => 'El Encanto', 'departament_id' => 1],
            ['name' => 'Miriti Paraná', 'departament_id' => 1],
            ['name' => 'La Chorrera', 'departament_id' => 1],
            ['name' => 'La Pedrera', 'departament_id' => 1],
            ['name' => 'La Victoria', 'departament_id' => 1],
            ['name' => 'Leticia', 'departament_id' => 1],
            ['name' => 'Mirití-Paraná', 'departament_id' => 1],
            ['name' => 'Puerto Alegría', 'departament_id' => 1],
            ['name' => 'Puerto Arica', 'departament_id' => 1],
            ['name' => 'Puerto Nariño', 'departament_id' => 1],
            ['name' => 'Puerto Santander', 'departament_id' => 1],
            ['name' => 'Tarapacá', 'departament_id' => 1],
            ['name' => 'Abejorral', 'departament_id' => 2],
            ['name' => 'Abriaquí', 'departament_id' => 2],
            ['name' => 'Alejandría', 'departament_id' => 2],
            ['name' => 'Amagá', 'departament_id' => 2],
            ['name' => 'Amalfi', 'departament_id' => 2],
            ['name' => 'Andes', 'departament_id' => 2],
            ['name' => 'Angelópolis', 'departament_id' => 2],
            ['name' => 'Angostura', 'departament_id' => 2],
            ['name' => 'Anorí', 'departament_id' => 2],
            ['name' => 'Anza', 'departament_id' => 2],
            ['name' => 'Apartadó', 'departament_id' => 2],
            ['name' => 'Arboletes', 'departament_id' => 2],
            ['name' => 'Argelia', 'departament_id' => 2],
            ['name' => 'Armenia', 'departament_id' => 2],
            ['name' => 'Barbosa', 'departament_id' => 2],
            ['name' => 'Belmira', 'departament_id' => 2],
            ['name' => 'Bello', 'departament_id' => 2],
            ['name' => 'Betania', 'departament_id' => 2],
            ['name' => 'Betulia', 'departament_id' => 2],
            ['name' => 'Briceño', 'departament_id' => 2],
            ['name' => 'Buriticá', 'departament_id' => 2],
            ['name' => 'Cáceres', 'departament_id' => 2],
            ['name' => 'Caicedo', 'departament_id' => 2],
            ['name' => 'Caldas', 'departament_id' => 2],
            ['name' => 'Campamento', 'departament_id' => 2],
            ['name' => 'Cañasgordas', 'departament_id' => 2],
            ['name' => 'Caracolí', 'departament_id' => 2],
            ['name' => 'Caramanta', 'departament_id' => 2],
            ['name' => 'Carepa', 'departament_id' => 2],
            ['name' => 'Carolina', 'departament_id' => 2],
            ['name' => 'Caucasia', 'departament_id' => 2],
            ['name' => 'Chigorodó', 'departament_id' => 2],
            ['name' => 'Cisneros', 'departament_id' => 2],
            ['name' => 'Ciudad Bolívar', 'departament_id' => 2],
            ['name' => 'Cocorná', 'departament_id' => 2],
            ['name' => 'Concepción', 'departament_id' => 2],
            ['name' => 'Concordia', 'departament_id' => 2],
            ['name' => 'Copacabana', 'departament_id' => 2],
            ['name' => 'Dabeiba', 'departament_id' => 2],
            ['name' => 'Don Matías', 'departament_id' => 2],
            ['name' => 'El Bagre', 'departament_id' => 2],
            ['name' => 'El Carmen de Viboral', 'departament_id' => 2],
            ['name' => 'El Santuario', 'departament_id' => 2],
            ['name' => 'Entrerrios', 'departament_id' => 2],
            ['name' => 'Envigado', 'departament_id' => 2],
            ['name' => 'Fredonia', 'departament_id' => 2],
            ['name' => 'Frontino', 'departament_id' => 2],
            ['name' => 'Giraldo', 'departament_id' => 2],
            ['name' => 'Girardota', 'departament_id' => 2],
            ['name' => 'Gómez Plata', 'departament_id' => 2],
            ['name' => 'Granada', 'departament_id' => 2],
            ['name' => 'Guadalupe', 'departament_id' => 2],
            ['name' => 'Guarne', 'departament_id' => 2],
            ['name' => 'Guatapé', 'departament_id' => 2],
            ['name' => 'Heliconia', 'departament_id' => 2],
            ['name' => 'Hispania', 'departament_id' => 2],
            ['name' => 'Itagüí', 'departament_id' => 2],
            ['name' => 'Ituango', 'departament_id' => 2],
            ['name' => 'Jardín', 'departament_id' => 2],
            ['name' => 'Jericó', 'departament_id' => 2],
            ['name' => 'La Ceja', 'departament_id' => 2],
            ['name' => 'La Estrella', 'departament_id' => 2],
            ['name' => 'La Pintada', 'departament_id' => 2],
            ['name' => 'La Unión', 'departament_id' => 2],
            ['name' => 'Liborina', 'departament_id' => 2],
            ['name' => 'Maceo', 'departament_id' => 2],
            ['name' => 'Marinilla', 'departament_id' => 2],
            ['name' => 'Medellín', 'departament_id' => 2],
            ['name' => 'Montebello', 'departament_id' => 2],
            ['name' => 'Murindó', 'departament_id' => 2],
            ['name' => 'Mutatá', 'departament_id' => 2],
            ['name' => 'Nariño', 'departament_id' => 2],
            ['name' => 'Nechí', 'departament_id' => 2],
            ['name' => 'Necoclí', 'departament_id' => 2],
            ['name' => 'Olaya', 'departament_id' => 2],
            ['name' => 'Peñol', 'departament_id' => 2],
            ['name' => 'Peque', 'departament_id' => 2],
            ['name' => 'Pueblorrico', 'departament_id' => 2],
            ['name' => 'Puerto Berrío', 'departament_id' => 2],
            ['name' => 'Puerto Nare', 'departament_id' => 2],
            ['name' => 'Puerto Triunfo', 'departament_id' => 2],
            ['name' => 'Remedios', 'departament_id' => 2],
            ['name' => 'El Retiro', 'departament_id' => 2],
            ['name' => 'Rionegro', 'departament_id' => 2],
            ['name' => 'Sabanalarga', 'departament_id' => 2],
            ['name' => 'Sabaneta', 'departament_id' => 2],
            ['name' => 'Salgar', 'departament_id' => 2],
            ['name' => 'San Andrés de Cuerquía', 'departament_id' => 2],
            ['name' => 'San Carlos', 'departament_id' => 2],
            ['name' => 'San Francisco', 'departament_id' => 2],
            ['name' => 'San Jerónimo', 'departament_id' => 2],
            ['name' => 'San José de La Montaña', 'departament_id' => 2],
            ['name' => 'San Juan de Urabá', 'departament_id' => 2],
            ['name' => 'San Luis', 'departament_id' => 2],
            ['name' => 'San Pedro de los Milagros', 'departament_id' => 2],
            ['name' => 'San Pedro de Uraba', 'departament_id' => 2],
            ['name' => 'San Rafael', 'departament_id' => 2],
            ['name' => 'San Roque', 'departament_id' => 2],
            ['name' => 'San Vicente', 'departament_id' => 2],
            ['name' => 'Santa Bárbara', 'departament_id' => 2],
            ['name' => 'Santa Rosa de Osos', 'departament_id' => 2],
            ['name' => 'Santafé de Antioquia', 'departament_id' => 2],
            ['name' => 'Santo Domingo', 'departament_id' => 2],
            ['name' => 'Segovia', 'departament_id' => 2],
            ['name' => 'Sonsón', 'departament_id' => 2],
            ['name' => 'Sopetrán', 'departament_id' => 2],
            ['name' => 'Támesis', 'departament_id' => 2],
            ['name' => 'Tarazá', 'departament_id' => 2],
            ['name' => 'Tarso', 'departament_id' => 2],
            ['name' => 'Titiribí', 'departament_id' => 2],
            ['name' => 'Toledo', 'departament_id' => 2],
            ['name' => 'Turbo', 'departament_id' => 2],
            ['name' => 'Uramita', 'departament_id' => 2],
            ['name' => 'Urrao', 'departament_id' => 2],
            ['name' => 'Valdivia', 'departament_id' => 2],
            ['name' => 'Valparaíso', 'departament_id' => 2],
            ['name' => 'Vegachí', 'departament_id' => 2],
            ['name' => 'Venecia', 'departament_id' => 2],
            ['name' => 'Vigía del Fuerte', 'departament_id' => 2],
            ['name' => 'Yalí', 'departament_id' => 2],
            ['name' => 'Yarumal', 'departament_id' => 2],
            ['name' => 'Yolombó', 'departament_id' => 2],
            ['name' => 'Yondó', 'departament_id' => 2],
            ['name' => 'Zaragoza', 'departament_id' => 2],
            ['name' => 'Arauca', 'departament_id' => 3],
            ['name' => 'Arauquita', 'departament_id' => 3],
            ['name' => 'Cravo Norte', 'departament_id' => 3],
            ['name' => 'Fortul', 'departament_id' => 3],
            ['name' => 'Puerto Nariño', 'departament_id' => 3],
            ['name' => 'Puerto Rondón', 'departament_id' => 3],
            ['name' => 'Saravena', 'departament_id' => 3],
            ['name' => 'Tame', 'departament_id' => 3],
            ['name' => 'Baranoa', 'departament_id' => 4],
            ['name' => 'Barranquilla', 'departament_id' => 4],
            ['name' => 'Campo de la Cruz', 'departament_id' => 4],
            ['name' => 'Candelaria', 'departament_id' => 4],
            ['name' => 'Galapa', 'departament_id' => 4],
            ['name' => 'Juan de Acosta', 'departament_id' => 4],
            ['name' => 'Luruaco', 'departament_id' => 4],
            ['name' => 'Malambo', 'departament_id' => 4],
            ['name' => 'Manatí', 'departament_id' => 4],
            ['name' => 'Palmar de Varela', 'departament_id' => 4],
            ['name' => 'Piojó', 'departament_id' => 4],
            ['name' => 'Polonuevo', 'departament_id' => 4],
            ['name' => 'Ponedera', 'departament_id' => 4],
            ['name' => 'Puerto Colombia', 'departament_id' => 4],
            ['name' => 'Repelón', 'departament_id' => 4],
            ['name' => 'Sabanagrande', 'departament_id' => 4],
            ['name' => 'Sabanalarga', 'departament_id' => 4],
            ['name' => 'Santa Lucía', 'departament_id' => 4],
            ['name' => 'Santo Tomás', 'departament_id' => 4],
            ['name' => 'Soledad', 'departament_id' => 4],
            ['name' => 'Suán', 'departament_id' => 4],
            ['name' => 'Tubará', 'departament_id' => 4],
            ['name' => 'Usiacurí', 'departament_id' => 4],
            ['name' => 'Bogotá', 'departament_id' => 5],
            ['name' => 'Achí', 'departament_id' => 6],
            ['name' => 'Altos del Rosario', 'departament_id' => 6],
            ['name' => 'Arenal', 'departament_id' => 6],
            ['name' => 'Arjona', 'departament_id' => 6],
            ['name' => 'Arroyohondo', 'departament_id' => 6],
            ['name' => 'Barranco de Loba', 'departament_id' => 6],
            ['name' => 'Calamar', 'departament_id' => 6],
            ['name' => 'Cantagallo', 'departament_id' => 6],
            ['name' => 'El Carmen de Bolívar', 'departament_id' => 6],
            ['name' => 'Cartagena de Indias', 'departament_id' => 6],
            ['name' => 'Cicuco', 'departament_id' => 6],
            ['name' => 'Clemencia', 'departament_id' => 6],
            ['name' => 'Córdoba', 'departament_id' => 6],
            ['name' => 'El Guamo', 'departament_id' => 6],
            ['name' => 'El Peñón', 'departament_id' => 6],
            ['name' => 'Hatillo de Loba', 'departament_id' => 6],
            ['name' => 'Magangué', 'departament_id' => 6],
            ['name' => 'Mahates', 'departament_id' => 6],
            ['name' => 'Margarita', 'departament_id' => 6],
            ['name' => 'María La Baja', 'departament_id' => 6],
            ['name' => 'Montecristo', 'departament_id' => 6],
            ['name' => 'Morales', 'departament_id' => 6],
            ['name' => 'Norosí', 'departament_id' => 6],
            ['name' => 'Pinillos', 'departament_id' => 6],
            ['name' => 'Regidor', 'departament_id' => 6],
            ['name' => 'Río Viejo', 'departament_id' => 6],
            ['name' => 'San Cristóbal', 'departament_id' => 6],
            ['name' => 'San Estanislao', 'departament_id' => 6],
            ['name' => 'San Fernando', 'departament_id' => 6],
            ['name' => 'San Jacinto', 'departament_id' => 6],
            ['name' => 'San Jacinto del Cauca', 'departament_id' => 6],
            ['name' => 'San Juan Nepomuceno', 'departament_id' => 6],
            ['name' => 'San Martín de Loba', 'departament_id' => 6],
            ['name' => 'San Pablo', 'departament_id' => 6],
            ['name' => 'Santa Catalina', 'departament_id' => 6],
            ['name' => 'Santa Cruz de Mompox', 'departament_id' => 6],
            ['name' => 'Santa Rosa', 'departament_id' => 6],
            ['name' => 'Santa Rosa del Sur', 'departament_id' => 6],
            ['name' => 'Simití', 'departament_id' => 6],
            ['name' => 'Soplaviento', 'departament_id' => 6],
            ['name' => 'Talaigua Nuevo', 'departament_id' => 6],
            ['name' => 'Tiquisio', 'departament_id' => 6],
            ['name' => 'Turbaco', 'departament_id' => 6],
            ['name' => 'Turbaná', 'departament_id' => 6],
            ['name' => 'Villanueva', 'departament_id' => 6],
            ['name' => 'Zambrano', 'departament_id' => 6],
            ['name' => 'Chíquiza', 'departament_id' => 7],
            ['name' => 'Chivatá', 'departament_id' => 7],
            ['name' => 'Cómbita', 'departament_id' => 7],
            ['name' => 'Cucaita', 'departament_id' => 7],
            ['name' => 'Motavita', 'departament_id' => 7],
            ['name' => 'Oicatá', 'departament_id' => 7],
            ['name' => 'Samacá', 'departament_id' => 7],
            ['name' => 'Siachoque', 'departament_id' => 7],
            ['name' => 'Sora', 'departament_id' => 7],
            ['name' => 'Soracá', 'departament_id' => 7],
            ['name' => 'Sotaquirá', 'departament_id' => 7],
            ['name' => 'Toca', 'departament_id' => 7],
            ['name' => 'Tunja', 'departament_id' => 7],
            ['name' => 'Tuta', 'departament_id' => 7],
            ['name' => 'Ventaquemada', 'departament_id' => 7],
            ['name' => 'Chiscas', 'departament_id' => 7],
            ['name' => 'El Cocuy', 'departament_id' => 7],
            ['name' => 'El Espino', 'departament_id' => 7],
            ['name' => 'Guacamayas', 'departament_id' => 7],
            ['name' => 'Güicán', 'departament_id' => 7],
            ['name' => 'Panqueba', 'departament_id' => 7],
            ['name' => 'Labranzagrande', 'departament_id' => 7],
            ['name' => 'Pajarito', 'departament_id' => 7],
            ['name' => 'Paya', 'departament_id' => 7],
            ['name' => 'Pisba', 'departament_id' => 7],
            ['name' => 'Berbeo', 'departament_id' => 7],
            ['name' => 'Campohermoso', 'departament_id' => 7],
            ['name' => 'Miraflores', 'departament_id' => 7],
            ['name' => 'Páez', 'departament_id' => 7],
            ['name' => 'San Eduardo', 'departament_id' => 7],
            ['name' => 'Zetaquira', 'departament_id' => 7],
            ['name' => 'Boyacá', 'departament_id' => 7],
            ['name' => 'Ciénega', 'departament_id' => 7],
            ['name' => 'Jenesano', 'departament_id' => 7],
            ['name' => 'Nuevo Colón', 'departament_id' => 7],
            ['name' => 'Ramiriquí', 'departament_id' => 7],
            ['name' => 'Rondón', 'departament_id' => 7],
            ['name' => 'Tibaná', 'departament_id' => 7],
            ['name' => 'Turmequé', 'departament_id' => 7],
            ['name' => 'Úmbita', 'departament_id' => 7],
            ['name' => 'Viracachá', 'departament_id' => 7],
            ['name' => 'Chinavita', 'departament_id' => 7],
            ['name' => 'Garagoa', 'departament_id' => 7],
            ['name' => 'Macanal', 'departament_id' => 7],
            ['name' => 'Pachavita', 'departament_id' => 7],
            ['name' => 'San Luis de Gaceno', 'departament_id' => 7],
            ['name' => 'Santa María	Neira', 'departament_id' => 7],
            ['name' => 'Boavita	Norte', 'departament_id' => 7],
            ['name' => 'Covarachía', 'departament_id' => 7],
            ['name' => 'La Uvita', 'departament_id' => 7],
            ['name' => 'San Mateo', 'departament_id' => 7],
            ['name' => 'Sativanorte', 'departament_id' => 7],
            ['name' => 'Sativasur', 'departament_id' => 7],
            ['name' => 'Soatá', 'departament_id' => 7],
            ['name' => 'Susacón', 'departament_id' => 7],
            ['name' => 'Tipacoque', 'departament_id' => 7],
            ['name' => 'Briceño', 'departament_id' => 7],
            ['name' => 'Buenavista', 'departament_id' => 7],
            ['name' => 'Caldas', 'departament_id' => 7],
            ['name' => 'Chiquinquirá', 'departament_id' => 7],
            ['name' => 'Coper', 'departament_id' => 7],
            ['name' => 'La Victoria', 'departament_id' => 7],
            ['name' => 'Maripí', 'departament_id' => 7],
            ['name' => 'Muzo', 'departament_id' => 7],
            ['name' => 'Otanche', 'departament_id' => 7],
            ['name' => 'Pauna', 'departament_id' => 7],
            ['name' => 'Quípama', 'departament_id' => 7],
            ['name' => 'Saboyá', 'departament_id' => 7],
            ['name' => 'San Miguel de Sema', 'departament_id' => 7],
            ['name' => 'San Pablo de Borbur', 'departament_id' => 7],
            ['name' => 'Tununguá', 'departament_id' => 7],
            ['name' => 'Almeida', 'departament_id' => 7],
            ['name' => 'Chivor', 'departament_id' => 7],
            ['name' => 'Guateque', 'departament_id' => 7],
            ['name' => 'Guayatá', 'departament_id' => 7],
            ['name' => 'La Capilla', 'departament_id' => 7],
            ['name' => 'Somondoco', 'departament_id' => 7],
            ['name' => 'Sutatenza', 'departament_id' => 7],
            ['name' => 'Tenza', 'departament_id' => 7],
            ['name' => 'Arcabuco', 'departament_id' => 7],
            ['name' => 'Chitaraque', 'departament_id' => 7],
            ['name' => 'Gachantivá', 'departament_id' => 7],
            ['name' => 'Moniquirá', 'departament_id' => 7],
            ['name' => 'Ráquira', 'departament_id' => 7],
            ['name' => 'Sáchica', 'departament_id' => 7],
            ['name' => 'San José de Pare', 'departament_id' => 7],
            ['name' => 'Santa Sofía', 'departament_id' => 7],
            ['name' => 'Santana', 'departament_id' => 7],
            ['name' => 'Sutamarchán', 'departament_id' => 7],
            ['name' => 'Tinjacá', 'departament_id' => 7],
            ['name' => 'Togüí', 'departament_id' => 7],
            ['name' => 'Villa de Leyva', 'departament_id' => 7],
            ['name' => 'Aquitania', 'departament_id' => 7],
            ['name' => 'Cuítiva', 'departament_id' => 7],
            ['name' => 'Firavitoba', 'departament_id' => 7],
            ['name' => 'Gámeza', 'departament_id' => 7],
            ['name' => 'Iza', 'departament_id' => 7],
            ['name' => 'Mongua', 'departament_id' => 7],
            ['name' => 'Monguí', 'departament_id' => 7],
            ['name' => 'Nobsa', 'departament_id' => 7],
            ['name' => 'Pesca', 'departament_id' => 7],
            ['name' => 'Sogamoso', 'departament_id' => 7],
            ['name' => 'Tibasosa', 'departament_id' => 7],
            ['name' => 'Tópaga', 'departament_id' => 7],
            ['name' => 'Tota', 'departament_id' => 7],
            ['name' => 'Belén', 'departament_id' => 7],
            ['name' => 'Busbanzá', 'departament_id' => 7],
            ['name' => 'Cerinza', 'departament_id' => 7],
            ['name' => 'Corrales', 'departament_id' => 7],
            ['name' => 'Duitama', 'departament_id' => 7],
            ['name' => 'Floresta', 'departament_id' => 7],
            ['name' => 'Paipa', 'departament_id' => 7],
            ['name' => 'Santa Rosa de Viterbo', 'departament_id' => 7],
            ['name' => 'Tutazá', 'departament_id' => 7],
            ['name' => 'Betéitiva', 'departament_id' => 7],
            ['name' => 'Chita', 'departament_id' => 7],
            ['name' => 'Jericó', 'departament_id' => 7],
            ['name' => 'Paz de Río', 'departament_id' => 7],
            ['name' => 'Socha', 'departament_id' => 7],
            ['name' => 'Socotá', 'departament_id' => 7],
            ['name' => 'Tasco', 'departament_id' => 7],
            ['name' => 'Cubará', 'departament_id' => 7],
            ['name' => 'Puerto Boyacá', 'departament_id' => 7],
            ['name' => 'Aguadas', 'departament_id' => 8],
            ['name' => 'Anserma', 'departament_id' => 8],
            ['name' => 'Aranzazu', 'departament_id' => 8],
            ['name' => 'Belalcazar', 'departament_id' => 8],
            ['name' => 'Chinchiná', 'departament_id' => 8],
            ['name' => 'Filadelfia', 'departament_id' => 8],
            ['name' => 'La Dorada', 'departament_id' => 8],
            ['name' => 'La Merced', 'departament_id' => 8],
            ['name' => 'Manizales', 'departament_id' => 8],
            ['name' => 'Manzanares', 'departament_id' => 8],
            ['name' => 'Marmato', 'departament_id' => 8],
            ['name' => 'Marquetalia', 'departament_id' => 8],
            ['name' => 'Marulanda', 'departament_id' => 8],
            ['name' => 'Neira', 'departament_id' => 8],
            ['name' => 'Norcasia', 'departament_id' => 8],
            ['name' => 'Pacora', 'departament_id' => 8],
            ['name' => 'Palestina', 'departament_id' => 8],
            ['name' => 'Pensilvania', 'departament_id' => 8],
            ['name' => 'Riosucio', 'departament_id' => 8],
            ['name' => 'Risaralda', 'departament_id' => 8],
            ['name' => 'Salamina', 'departament_id' => 8],
            ['name' => 'Samana', 'departament_id' => 8],
            ['name' => 'San Jose', 'departament_id' => 8],
            ['name' => 'Supía', 'departament_id' => 8],
            ['name' => 'Victoria', 'departament_id' => 8],
            ['name' => 'Villamaría', 'departament_id' => 8],
            ['name' => 'Viterbo', 'departament_id' => 8],
            ['name' => 'Albania', 'departament_id' => 9], //Caquetá
            ['name' => 'Belén de los Andaquies', 'departament_id' => 9],
            ['name' => 'Cartagena del Chairá', 'departament_id' => 9],
            ['name' => 'Currillo', 'departament_id' => 9],
            ['name' => 'El Doncello', 'departament_id' => 9],
            ['name' => 'El Paujil', 'departament_id' => 9],
            ['name' => 'Florencia', 'departament_id' => 9],
            ['name' => 'La Montañita', 'departament_id' => 9],
            ['name' => 'Morelia', 'departament_id' => 9],
            ['name' => 'Puerto Milán', 'departament_id' => 9],
            ['name' => 'Puerto Rico', 'departament_id' => 9],
            ['name' => 'San José del Fragua', 'departament_id' => 9],
            ['name' => 'San Vicente del Caguán', 'departament_id' => 9],
            ['name' => 'Solano', 'departament_id' => 9],
            ['name' => 'Solita', 'departament_id' => 9],
            ['name' => 'Valparaíso', 'departament_id' => 9],
            ['name' => 'Aguazul', 'departament_id' => 10],
            ['name' => 'Chámeza', 'departament_id' => 10],
            ['name' => 'Hato Corozal', 'departament_id' => 10],
            ['name' => 'La Salina', 'departament_id' => 10],
            ['name' => 'Maní', 'departament_id' => 10],
            ['name' => 'Monterrey', 'departament_id' => 10],
            ['name' => 'Nunchía', 'departament_id' => 10],
            ['name' => 'Orocué', 'departament_id' => 10],
            ['name' => 'Paz de Ariporo', 'departament_id' => 10],
            ['name' => 'Pore', 'departament_id' => 10],
            ['name' => 'Recetor', 'departament_id' => 10],
            ['name' => 'Sabanalarga', 'departament_id' => 10],
            ['name' => 'Sácama', 'departament_id' => 10],
            ['name' => 'San Luis de Palenque', 'departament_id' => 10],
            ['name' => 'Támara', 'departament_id' => 10],
            ['name' => 'Tauramena', 'departament_id' => 10],
            ['name' => 'Trinidad', 'departament_id' => 10],
            ['name' => 'Villanueva', 'departament_id' => 10],
            ['name' => 'Yopal', 'departament_id' => 10],
            ['name' => 'Buenos Aires', 'departament_id' => 11], //Cauca
            ['name' => 'Caloto', 'departament_id' => 11],
            ['name' => 'Corinto', 'departament_id' => 11],
            ['name' => 'Guachené', 'departament_id' => 11],
            ['name' => 'Guapi', 'departament_id' => 11],
            ['name' => 'Miranda', 'departament_id' => 11],
            ['name' => 'Padilla', 'departament_id' => 11],
            ['name' => 'Puerto Tejada', 'departament_id' => 11],
            ['name' => 'Santander de Quilichao', 'departament_id' => 11],
            ['name' => 'Suárez', 'departament_id' => 11],
            ['name' => 'Villa Rica', 'departament_id' => 11],
            ['name' => 'Cajibío', 'departament_id' => 11],
            ['name' => 'El Tambo', 'departament_id' => 11],
            ['name' => 'La Sierra', 'departament_id' => 11],
            ['name' => 'Morales', 'departament_id' => 11],
            ['name' => 'Piendamó', 'departament_id' => 11],
            ['name' => 'Popayán', 'departament_id' => 11],
            ['name' => 'Rosas', 'departament_id' => 11],
            ['name' => 'Sotará', 'departament_id' => 11],
            ['name' => 'Timbío', 'departament_id' => 11],
            ['name' => 'Almaguer', 'departament_id' => 11],
            ['name' => 'Argelia', 'departament_id' => 11],
            ['name' => 'Balboa', 'departament_id' => 11],
            ['name' => 'Bolívar', 'departament_id' => 11],
            ['name' => 'Florencia', 'departament_id' => 11],
            ['name' => 'La Vega', 'departament_id' => 11],
            ['name' => 'Mercaderes', 'departament_id' => 11],
            ['name' => 'Patía', 'departament_id' => 11],
            ['name' => 'Piamonte', 'departament_id' => 11],
            ['name' => 'San Sebastián', 'departament_id' => 11],
            ['name' => 'Santa Rosa', 'departament_id' => 11],
            ['name' => 'Sotara', 'departament_id' => 11],
            ['name' => 'Sucre', 'departament_id' => 11],
            ['name' => 'Guapí', 'departament_id' => 11],
            ['name' => 'López de Micay', 'departament_id' => 11],
            ['name' => 'Timbiquí', 'departament_id' => 11],
            ['name' => 'Caldono', 'departament_id' => 11],
            ['name' => 'Inzá', 'departament_id' => 11],
            ['name' => 'Jambaló', 'departament_id' => 11],
            ['name' => 'Páez', 'departament_id' => 11],
            ['name' => 'Puracé (Coconuco)', 'departament_id' => 11],
            ['name' => 'Silvia', 'departament_id' => 11],
            ['name' => 'Toribío', 'departament_id' => 11],
            ['name' => 'Totoró', 'departament_id' => 11],
            ['name' => 'Valledupar', 'departament_id' => 12], //Cesar
            ['name' => 'Aguachica', 'departament_id' => 12],
            ['name' => 'Agustín Codazzi', 'departament_id' => 12],
            ['name' => 'Bosconia', 'departament_id' => 12],
            ['name' => 'Chimichagua', 'departament_id' => 12],
            ['name' => 'El Copey', 'departament_id' => 12],
            ['name' => 'San Alberto', 'departament_id' => 12],
            ['name' => 'Curumaní', 'departament_id' => 12],
            ['name' => 'El Paso', 'departament_id' => 12],
            ['name' => 'La Paz', 'departament_id' => 12],
            ['name' => 'Pueblo Bello', 'departament_id' => 12],
            ['name' => 'La Jagua de Ibirico', 'departament_id' => 12],
            ['name' => 'Chiriguaná', 'departament_id' => 12],
            ['name' => 'Astrea', 'departament_id' => 12],
            ['name' => 'San Martín', 'departament_id' => 12],
            ['name' => 'Pelaya', 'departament_id' => 12],
            ['name' => 'Pailitas', 'departament_id' => 12],
            ['name' => 'Gamarra', 'departament_id' => 12],
            ['name' => 'Manaure Balcón del Cesar', 'departament_id' => 12],
            ['name' => 'Río de Oro', 'departament_id' => 12],
            ['name' => 'Tamalameque', 'departament_id' => 12],
            ['name' => 'Becerril', 'departament_id' => 12],
            ['name' => 'San Diego', 'departament_id' => 12],
            ['name' => 'La Gloria', 'departament_id' => 12],
            ['name' => 'González', 'departament_id' => 12],
            ['name' => 'Cesar', 'departament_id' => 12],
            ['name' => 'Acandí', 'departament_id' => 13], //Chocó
            ['name' => 'Alto Baudó', 'departament_id' => 13],
            ['name' => 'Atrato', 'departament_id' => 13],
            ['name' => 'Bagadó', 'departament_id' => 13],
            ['name' => 'Bahía Solano', 'departament_id' => 13],
            ['name' => 'Bajo Baudó', 'departament_id' => 13],
            ['name' => 'Belén de Bajira', 'departament_id' => 13],
            ['name' => 'Bojayá', 'departament_id' => 13],
            ['name' => 'Carmen del Darien', 'departament_id' => 13],
            ['name' => 'Certegui', 'departament_id' => 13],
            ['name' => 'Condoto', 'departament_id' => 13],
            ['name' => 'El Carmen de Atrato', 'departament_id' => 13],
            ['name' => 'El Cantón del San Pablo', 'departament_id' => 13],
            ['name' => 'El Litoral del San Juan', 'departament_id' => 13],
            ['name' => 'Istmina', 'departament_id' => 13],
            ['name' => 'Juradó', 'departament_id' => 13],
            ['name' => 'Litoral de San Juan', 'departament_id' => 13],
            ['name' => 'Lloró', 'departament_id' => 13],
            ['name' => 'Medio Atrato', 'departament_id' => 13],
            ['name' => 'Medio Baudo', 'departament_id' => 13],
            ['name' => 'Medio San Juan', 'departament_id' => 13],
            ['name' => 'Nóvita', 'departament_id' => 13],
            ['name' => 'Nuquí', 'departament_id' => 13],
            ['name' => 'Quibdó', 'departament_id' => 13],
            ['name' => 'Río Iró', 'departament_id' => 13],
            ['name' => 'Rio Quito', 'departament_id' => 13],
            ['name' => 'Riosucio', 'departament_id' => 13],
            ['name' => 'San José del Palmar', 'departament_id' => 13],
            ['name' => 'Sipí', 'departament_id' => 13],
            ['name' => 'Tadó', 'departament_id' => 13],
            ['name' => 'Unguía', 'departament_id' => 13],
            ['name' => 'Unión Panamericana', 'departament_id' => 13],
            ['name' => 'Ayapel', 'departament_id' => 14], //CORDOBA
            ['name' => 'Buenavista', 'departament_id' => 14],
            ['name' => 'Canalete', 'departament_id' => 14],
            ['name' => 'Cereté', 'departament_id' => 14],
            ['name' => 'Chimá', 'departament_id' => 14],
            ['name' => 'Chinú', 'departament_id' => 14],
            ['name' => 'Ciénaga de Oro', 'departament_id' => 14],
            ['name' => 'Cotorra', 'departament_id' => 14],
            ['name' => 'La Apartada', 'departament_id' => 14],
            ['name' => 'Los Córdobas', 'departament_id' => 14],
            ['name' => 'Momil', 'departament_id' => 14],
            ['name' => 'Montelíbano', 'departament_id' => 14],
            ['name' => 'Montería', 'departament_id' => 14],
            ['name' => 'Moñitos', 'departament_id' => 14],
            ['name' => 'Planeta Rica', 'departament_id' => 14],
            ['name' => 'Pueblo Nuevo', 'departament_id' => 14],
            ['name' => 'Puerto Escondido', 'departament_id' => 14],
            ['name' => 'Puerto Libertador', 'departament_id' => 14],
            ['name' => 'Purísima', 'departament_id' => 14],
            ['name' => 'Sahagún', 'departament_id' => 14],
            ['name' => 'San Andrés de Sotavento', 'departament_id' => 14],
            ['name' => 'San Antero', 'departament_id' => 14],
            ['name' => 'San Bernardo del Viento', 'departament_id' => 14],
            ['name' => 'San Carlos', 'departament_id' => 14],
            ['name' => 'San José de Uré', 'departament_id' => 14],
            ['name' => 'San Pelayo', 'departament_id' => 14],
            ['name' => 'Santa Cruz de Lorica', 'departament_id' => 14],
            ['name' => 'Tierralta', 'departament_id' => 14],
            ['name' => 'Tuchín', 'departament_id' => 14],
            ['name' => 'Valencia', 'departament_id' => 14],
            ['name' => 'Chocontá', 'departament_id' => 15], //Cundinamarca
            ['name' => 'Machetá', 'departament_id' => 15],
            ['name' => 'Manta', 'departament_id' => 15],
            ['name' => 'Sesquilé', 'departament_id' => 15],
            ['name' => 'Suesca', 'departament_id' => 15],
            ['name' => 'Tibirita', 'departament_id' => 15],
            ['name' => 'Villapinzón', 'departament_id' => 15],
            ['name' => 'Agua de Dios', 'departament_id' => 15],
            ['name' => 'Girardot', 'departament_id' => 15],
            ['name' => 'Guataquí', 'departament_id' => 15],
            ['name' => 'Jerusalén', 'departament_id' => 15],
            ['name' => 'Nariño', 'departament_id' => 15],
            ['name' => 'Nilo', 'departament_id' => 15],
            ['name' => 'Ricaurte', 'departament_id' => 15],
            ['name' => 'Tocaima', 'departament_id' => 15],
            ['name' => 'Caparrapí', 'departament_id' => 15],
            ['name' => 'Guaduas', 'departament_id' => 15],
            ['name' => 'Puerto Salgar', 'departament_id' => 15],
            ['name' => 'Albán', 'departament_id' => 15],
            ['name' => 'La Peña', 'departament_id' => 15],
            ['name' => 'La Vega', 'departament_id' => 15],
            ['name' => 'Nimaima', 'departament_id' => 15],
            ['name' => 'Nocaima', 'departament_id' => 15],
            ['name' => 'Quebradanegra', 'departament_id' => 15],
            ['name' => 'San Francisco', 'departament_id' => 15],
            ['name' => 'Sasaima', 'departament_id' => 15],
            ['name' => 'Supatá', 'departament_id' => 15],
            ['name' => 'Útica', 'departament_id' => 15],
            ['name' => 'Vergara', 'departament_id' => 15],
            ['name' => 'Villeta', 'departament_id' => 15],
            ['name' => 'Gachalá', 'departament_id' => 15],
            ['name' => 'Gachetá', 'departament_id' => 15],
            ['name' => 'Gama', 'departament_id' => 15],
            ['name' => 'Guasca', 'departament_id' => 15],
            ['name' => 'Guatavita', 'departament_id' => 15],
            ['name' => 'Junín', 'departament_id' => 15],
            ['name' => 'La Calera', 'departament_id' => 15],
            ['name' => 'Ubalá', 'departament_id' => 15],
            ['name' => 'Beltrán', 'departament_id' => 15],
            ['name' => 'Bituima', 'departament_id' => 15],
            ['name' => 'Chaguaní', 'departament_id' => 15],
            ['name' => 'Guayabal de Síquima', 'departament_id' => 15],
            ['name' => 'Pulí', 'departament_id' => 15],
            ['name' => 'San Juan de Rio Seco', 'departament_id' => 15],
            ['name' => 'Vianí', 'departament_id' => 15],
            ['name' => 'Medina', 'departament_id' => 15],
            ['name' => 'Paratebueno', 'departament_id' => 15],
            ['name' => 'Cáqueza', 'departament_id' => 15],
            ['name' => 'Chipaque', 'departament_id' => 15],
            ['name' => 'Choachí', 'departament_id' => 15],
            ['name' => 'Fómeque', 'departament_id' => 15],
            ['name' => 'Fosca', 'departament_id' => 15],
            ['name' => 'Guayabetal', 'departament_id' => 15],
            ['name' => 'Gutiérrez', 'departament_id' => 15],
            ['name' => 'Quetame', 'departament_id' => 15],
            ['name' => 'Ubaque', 'departament_id' => 15],
            ['name' => 'Une', 'departament_id' => 15],
            ['name' => 'El Peñón', 'departament_id' => 15],
            ['name' => 'La Palma', 'departament_id' => 15],
            ['name' => 'Pacho', 'departament_id' => 15],
            ['name' => 'Paime', 'departament_id' => 15],
            ['name' => 'San Cayetano', 'departament_id' => 15],
            ['name' => 'Topaipí', 'departament_id' => 15],
            ['name' => 'Villagómez', 'departament_id' => 15],
            ['name' => 'Yacopí', 'departament_id' => 15],
            ['name' => 'Cajicá', 'departament_id' => 15],
            ['name' => 'Chía', 'departament_id' => 15],
            ['name' => 'Cogua', 'departament_id' => 15],
            ['name' => 'Gachancipá', 'departament_id' => 15],
            ['name' => 'Nemocón', 'departament_id' => 15],
            ['name' => 'Sopó', 'departament_id' => 15],
            ['name' => 'Tabio', 'departament_id' => 15],
            ['name' => 'Tenjo', 'departament_id' => 15],
            ['name' => 'Tocancipá', 'departament_id' => 15],
            ['name' => 'Zipaquirá', 'departament_id' => 15],
            ['name' => 'Bojacá', 'departament_id' => 15],
            ['name' => 'Cota', 'departament_id' => 15],
            ['name' => 'El Rosal', 'departament_id' => 15],
            ['name' => 'Facatativá', 'departament_id' => 15],
            ['name' => 'Funza', 'departament_id' => 15],
            ['name' => 'Madrid', 'departament_id' => 15],
            ['name' => 'Mosquera', 'departament_id' => 15],
            ['name' => 'Subachoque', 'departament_id' => 15],
            ['name' => 'Zipacón', 'departament_id' => 15],
            ['name' => 'Sibaté', 'departament_id' => 15],
            ['name' => 'Soacha', 'departament_id' => 15],
            ['name' => 'Arbeláez', 'departament_id' => 15],
            ['name' => 'Cabrera', 'departament_id' => 15],
            ['name' => 'Fusagasugá', 'departament_id' => 15],
            ['name' => 'Granada', 'departament_id' => 15],
            ['name' => 'Pandi', 'departament_id' => 15],
            ['name' => 'Pasca', 'departament_id' => 15],
            ['name' => 'San Bernardo', 'departament_id' => 15],
            ['name' => 'Silvania', 'departament_id' => 15],
            ['name' => 'Tibacuy', 'departament_id' => 15],
            ['name' => 'Venecia', 'departament_id' => 15],
            ['name' => 'Anapoima', 'departament_id' => 15],
            ['name' => 'Anolaima', 'departament_id' => 15],
            ['name' => 'Apulo', 'departament_id' => 15],
            ['name' => 'Cachipay', 'departament_id' => 15],
            ['name' => 'El Colegio', 'departament_id' => 15],
            ['name' => 'La Mesa', 'departament_id' => 15],
            ['name' => 'Quipile', 'departament_id' => 15],
            ['name' => 'San Antonio del Tequendama', 'departament_id' => 15],
            ['name' => 'Tena', 'departament_id' => 15],
            ['name' => 'Viotá', 'departament_id' => 15],
            ['name' => 'Carmen de Carupa', 'departament_id' => 15],
            ['name' => 'Cucunubá', 'departament_id' => 15],
            ['name' => 'Fúquene', 'departament_id' => 15],
            ['name' => 'Guachetá', 'departament_id' => 15],
            ['name' => 'Lenguazaque', 'departament_id' => 15],
            ['name' => 'Simijaca', 'departament_id' => 15],
            ['name' => 'Susa', 'departament_id' => 15],
            ['name' => 'Sutatausa', 'departament_id' => 15],
            ['name' => 'Tausa', 'departament_id' => 15],
            ['name' => 'Ubaté', 'departament_id' => 15],
            ['name' => 'Villa de San Diego de Ubate', 'departament_id' => 15],
            ['name' => 'Barranco Minas', 'departament_id' => 16], //Guainía
            ['name' => 'Cacahual', 'departament_id' => 16],
            ['name' => 'Inírida', 'departament_id' => 16],
            ['name' => 'La Guadalupe', 'departament_id' => 16],
            ['name' => 'Mapiripana', 'departament_id' => 16],
            ['name' => 'Morichal', 'departament_id' => 16],
            ['name' => 'Pana Pana', 'departament_id' => 16],
            ['name' => 'Puerto Colombia', 'departament_id' => 16],
            ['name' => 'San Felipe', 'departament_id' => 16],
            ['name' => 'Calamar', 'departament_id' => 17], //Guaviare
            ['name' => 'El Retorno', 'departament_id' => 17],
            ['name' => 'Miraflores', 'departament_id' => 17],
            ['name' => 'San José del Guaviare', 'departament_id' => 17],
            ['name' => 'Aipe', 'departament_id' => 18], //Huila
            ['name' => 'Algeciras', 'departament_id' => 18],
            ['name' => 'Baraya', 'departament_id' => 18],
            ['name' => 'Campoalegre', 'departament_id' => 18],
            ['name' => 'Colombia', 'departament_id' => 18],
            ['name' => 'Hobo', 'departament_id' => 18],
            ['name' => 'Íquira', 'departament_id' => 18],
            ['name' => 'Neiva', 'departament_id' => 18],
            ['name' => 'Palermo', 'departament_id' => 18],
            ['name' => 'Rivera', 'departament_id' => 18],
            ['name' => 'Santa María', 'departament_id' => 18],
            ['name' => 'Tello', 'departament_id' => 18],
            ['name' => 'Teruel', 'departament_id' => 18],
            ['name' => 'Villavieja', 'departament_id' => 18],
            ['name' => 'Yaguará', 'departament_id' => 18],
            ['name' => 'Agrado', 'departament_id' => 18],
            ['name' => 'Altamira', 'departament_id' => 18],
            ['name' => 'Garzón', 'departament_id' => 18],
            ['name' => 'Gigante', 'departament_id' => 18],
            ['name' => 'Guadalupe', 'departament_id' => 18],
            ['name' => 'Pital', 'departament_id' => 18],
            ['name' => 'Suaza', 'departament_id' => 18],
            ['name' => 'Tarqui', 'departament_id' => 18],
            ['name' => 'La Argentina', 'departament_id' => 18],
            ['name' => 'La Plata', 'departament_id' => 18],
            ['name' => 'Nátaga', 'departament_id' => 18],
            ['name' => 'Paicol', 'departament_id' => 18],
            ['name' => 'Tesalia', 'departament_id' => 18],
            ['name' => 'Acevedo', 'departament_id' => 18],
            ['name' => 'Elías', 'departament_id' => 18],
            ['name' => 'Isnos', 'departament_id' => 18],
            ['name' => 'Oporapa', 'departament_id' => 18],
            ['name' => 'Palestina', 'departament_id' => 18],
            ['name' => 'Pitalito', 'departament_id' => 18],
            ['name' => 'Saladoblanco', 'departament_id' => 18],
            ['name' => 'San Agustín', 'departament_id' => 18],
            ['name' => 'Timaná', 'departament_id' => 18],
            ['name' => 'Albania', 'departament_id' => 19], //La Guajira
            ['name' => 'Barrancas', 'departament_id' => 19],
            ['name' => 'Dibulla', 'departament_id' => 19],
            ['name' => 'Distracción', 'departament_id' => 19],
            ['name' => 'El Molino', 'departament_id' => 19],
            ['name' => 'Fonseca', 'departament_id' => 19],
            ['name' => 'Hatonuevo', 'departament_id' => 19],
            ['name' => 'La Jagua del Pilar', 'departament_id' => 19],
            ['name' => 'Maicao', 'departament_id' => 19],
            ['name' => 'Manaure', 'departament_id' => 19],
            ['name' => 'Riohacha', 'departament_id' => 19],
            ['name' => 'San Juan del Cesar', 'departament_id' => 19],
            ['name' => 'Uribia', 'departament_id' => 19],
            ['name' => 'Urumita', 'departament_id' => 19],
            ['name' => 'Villanueva', 'departament_id' => 19],
            ['name' => 'Algarrobo', 'departament_id' => 20], //Magdalena
            ['name' => 'Aracataca', 'departament_id' => 20],
            ['name' => 'Ariguaní', 'departament_id' => 20],
            ['name' => 'Cerro de San Antonio', 'departament_id' => 20],
            ['name' => 'Chibolo', 'departament_id' => 20],
            ['name' => 'Ciénaga', 'departament_id' => 20],
            ['name' => 'Concordia', 'departament_id' => 20],
            ['name' => 'El Banco', 'departament_id' => 20],
            ['name' => 'El Piñón', 'departament_id' => 20],
            ['name' => 'El Retén', 'departament_id' => 20],
            ['name' => 'Fundación', 'departament_id' => 20],
            ['name' => 'Guamal', 'departament_id' => 20],
            ['name' => 'Nueva Granada', 'departament_id' => 20],
            ['name' => 'Pedraza', 'departament_id' => 20],
            ['name' => 'Pijiño del Carmen', 'departament_id' => 20],
            ['name' => 'Pivijay', 'departament_id' => 20],
            ['name' => 'Plato', 'departament_id' => 20],
            ['name' => 'Pueblo Viejo', 'departament_id' => 20],
            ['name' => 'Remolino', 'departament_id' => 20],
            ['name' => 'Sabanas de San Ángel', 'departament_id' => 20],
            ['name' => 'Salamina', 'departament_id' => 20],
            ['name' => 'San Sebastián de Buenavista', 'departament_id' => 20],
            ['name' => 'Santa Ana', 'departament_id' => 20],
            ['name' => 'Santa Bárbara', 'departament_id' => 20],
            ['name' => 'Santa Marta', 'departament_id' => 20],
            ['name' => 'San Zenón', 'departament_id' => 20],
            ['name' => 'Sitionuevo', 'departament_id' => 20],
            ['name' => 'Tenerife', 'departament_id' => 20],
            ['name' => 'Zapayán', 'departament_id' => 20],
            ['name' => 'Zona Bananera', 'departament_id' => 20],
            ['name' => 'Acacías', 'departament_id' => 21], //Meta
            ['name' => 'Barranca de Upía', 'departament_id' => 21],
            ['name' => 'Cabuyaro', 'departament_id' => 21],
            ['name' => 'Castilla La Nueva', 'departament_id' => 21],
            ['name' => 'Cubarral', 'departament_id' => 21],
            ['name' => 'Cumaral', 'departament_id' => 21],
            ['name' => 'El Calvario', 'departament_id' => 21],
            ['name' => 'El Castillo', 'departament_id' => 21],
            ['name' => 'El Dorado', 'departament_id' => 21],
            ['name' => 'Fuente de Oro', 'departament_id' => 21],
            ['name' => 'Granada', 'departament_id' => 21],
            ['name' => 'Guamal', 'departament_id' => 21],
            ['name' => 'La Macarena', 'departament_id' => 21],
            ['name' => 'La Uribe', 'departament_id' => 21],
            ['name' => 'Lejanías', 'departament_id' => 21],
            ['name' => 'Mapiripán', 'departament_id' => 21],
            ['name' => 'Mesetas', 'departament_id' => 21],
            ['name' => 'Puerto Concordia', 'departament_id' => 21],
            ['name' => 'Puerto Gaitán', 'departament_id' => 21],
            ['name' => 'Puerto Lleras', 'departament_id' => 21],
            ['name' => 'Puerto López', 'departament_id' => 21],
            ['name' => 'Puerto Rico', 'departament_id' => 21],
            ['name' => 'Restrepo', 'departament_id' => 21],
            ['name' => 'San Carlos de Guaroa', 'departament_id' => 21],
            ['name' => 'San Juan de Arama', 'departament_id' => 21],
            ['name' => 'San Juanito', 'departament_id' => 21],
            ['name' => 'San Martín', 'departament_id' => 21],
            ['name' => 'Villavicencio', 'departament_id' => 21],
            ['name' => 'Vista Hermosa', 'departament_id' => 21],
            ['name' => 'Albán', 'departament_id' => 22], //Nariño
            ['name' => 'Aldana', 'departament_id' => 22],
            ['name' => 'Ancuya', 'departament_id' => 22],
            ['name' => 'Arboleda', 'departament_id' => 22],
            ['name' => 'Barbacoas', 'departament_id' => 22],
            ['name' => 'Belén', 'departament_id' => 22],
            ['name' => 'Buesaco', 'departament_id' => 22],
            ['name' => 'Chachagüí', 'departament_id' => 22],
            ['name' => 'Colón', 'departament_id' => 22],
            ['name' => 'Consaca', 'departament_id' => 22],
            ['name' => 'Contadero', 'departament_id' => 22],
            ['name' => 'Córdoba', 'departament_id' => 22],
            ['name' => 'Cuaspud', 'departament_id' => 22],
            ['name' => 'Cumbal', 'departament_id' => 22],
            ['name' => 'Cumbitara', 'departament_id' => 22],
            ['name' => 'El Charco', 'departament_id' => 22],
            ['name' => 'El Peñol', 'departament_id' => 22],
            ['name' => 'El Rosario', 'departament_id' => 22],
            ['name' => 'El Tablón', 'departament_id' => 22],
            ['name' => 'El Tambo', 'departament_id' => 22],
            ['name' => 'Francisco Pizarro', 'departament_id' => 22],
            ['name' => 'Funes', 'departament_id' => 22],
            ['name' => 'Guachucal', 'departament_id' => 22],
            ['name' => 'Guaitarilla', 'departament_id' => 22],
            ['name' => 'Gualmatán', 'departament_id' => 22],
            ['name' => 'Iles', 'departament_id' => 22],
            ['name' => 'Imues', 'departament_id' => 22],
            ['name' => 'Ipiales', 'departament_id' => 22],
            ['name' => 'La Cruz', 'departament_id' => 22],
            ['name' => 'La Florida', 'departament_id' => 22],
            ['name' => 'La Llanada', 'departament_id' => 22],
            ['name' => 'La Tola', 'departament_id' => 22],
            ['name' => 'La Unión', 'departament_id' => 22],
            ['name' => 'Leiva', 'departament_id' => 22],
            ['name' => 'Linares', 'departament_id' => 22],
            ['name' => 'Los Andes', 'departament_id' => 22],
            ['name' => 'Magui', 'departament_id' => 22],
            ['name' => 'Mallama', 'departament_id' => 22],
            ['name' => 'Mosquera', 'departament_id' => 22],
            ['name' => 'Nariño', 'departament_id' => 22],
            ['name' => 'Olaya Herrera', 'departament_id' => 22],
            ['name' => 'Ospina', 'departament_id' => 22],
            ['name' => 'Pasto', 'departament_id' => 22],
            ['name' => 'Policarpa', 'departament_id' => 22],
            ['name' => 'Potosí', 'departament_id' => 22],
            ['name' => 'Providencia', 'departament_id' => 22],
            ['name' => 'Puerres', 'departament_id' => 22],
            ['name' => 'Pupiales', 'departament_id' => 22],
            ['name' => 'Ricaurte', 'departament_id' => 22],
            ['name' => 'Roberto Payán', 'departament_id' => 22],
            ['name' => 'Samaniego', 'departament_id' => 22],
            ['name' => 'San Andrés de Tumaco', 'departament_id' => 22],
            ['name' => 'San Bernardo', 'departament_id' => 22],
            ['name' => 'San Lorenzo', 'departament_id' => 22],
            ['name' => 'San Pablo', 'departament_id' => 22],
            ['name' => 'San Pedro de Cartago', 'departament_id' => 22],
            ['name' => 'Sandona', 'departament_id' => 22],
            ['name' => 'Santa Barbara', 'departament_id' => 22],
            ['name' => 'Santacruz', 'departament_id' => 22],
            ['name' => 'Sapuyes', 'departament_id' => 22],
            ['name' => 'Taminango', 'departament_id' => 22],
            ['name' => 'Tangua', 'departament_id' => 22],
            ['name' => 'Tumaco', 'departament_id' => 22],
            ['name' => 'Tuquerres', 'departament_id' => 22],
            ['name' => 'Yacuanquer', 'departament_id' => 22],
            ['name' => 'Arboledas', 'departament_id' => 23], //norte santander
            ['name' => 'Abrego', 'departament_id' => 23],
            ['name' => 'Cachirá', 'departament_id' => 23],
            ['name' => 'Cucutilla', 'departament_id' => 23],
            ['name' => 'Gramalote', 'departament_id' => 23],
            ['name' => 'Lourdes', 'departament_id' => 23],
            ['name' => 'Salazar de Las Palmas', 'departament_id' => 23],
            ['name' => 'Santiago', 'departament_id' => 23],
            ['name' => 'Villa Caro', 'departament_id' => 23],
            ['name' => 'Cúcuta', 'departament_id' => 23],
            ['name' => 'El Zulia', 'departament_id' => 23],
            ['name' => 'Los Patios', 'departament_id' => 23],
            ['name' => 'Puerto Santander', 'departament_id' => 23],
            ['name' => 'San Cayetano', 'departament_id' => 23],
            ['name' => 'Villa del Rosario', 'departament_id' => 23],
            ['name' => 'Bucarasica', 'departament_id' => 23],
            ['name' => 'El Tarra', 'departament_id' => 23],
            ['name' => 'Sardinata', 'departament_id' => 23],
            ['name' => 'Tibú', 'departament_id' => 23],
            ['name' => 'Ábrego', 'departament_id' => 23],
            ['name' => 'Cáchira', 'departament_id' => 23],
            ['name' => 'Convención', 'departament_id' => 23],
            ['name' => 'El Carmen', 'departament_id' => 23],
            ['name' => 'Hacarí', 'departament_id' => 23],
            ['name' => 'La Esperanza', 'departament_id' => 23],
            ['name' => 'La Playa de Belén', 'departament_id' => 23],
            ['name' => 'Ocaña', 'departament_id' => 23],
            ['name' => 'San Calixto', 'departament_id' => 23],
            ['name' => 'Teorama', 'departament_id' => 23],
            ['name' => 'Cácota', 'departament_id' => 23],
            ['name' => 'Chitagá', 'departament_id' => 23],
            ['name' => 'Mutiscua', 'departament_id' => 23],
            ['name' => 'Pamplona', 'departament_id' => 23],
            ['name' => 'Pamplonita', 'departament_id' => 23],
            ['name' => 'Santo Domingo de Silos', 'departament_id' => 23],
            ['name' => 'Bochalema', 'departament_id' => 23],
            ['name' => 'Chinácota', 'departament_id' => 23],
            ['name' => 'Durania', 'departament_id' => 23],
            ['name' => 'Herrán', 'departament_id' => 23],
            ['name' => 'Labateca', 'departament_id' => 23],
            ['name' => 'Ragonvalia', 'departament_id' => 23],
            ['name' => 'Toledo', 'departament_id' => 23],
            ['name' => 'Colón', 'departament_id' => 24],//Putumayo
            ['name' => 'Mocoa', 'departament_id' => 24],
            ['name' => 'Orito', 'departament_id' => 24],
            ['name' => 'Puerto Asís', 'departament_id' => 24],
            ['name' => 'Puerto Caicedo', 'departament_id' => 24],
            ['name' => 'Puerto Guzmán', 'departament_id' => 24],
            ['name' => 'Puerto Leguízamo', 'departament_id' => 24],
            ['name' => 'San Francisco', 'departament_id' => 24],
            ['name' => 'San Miguel', 'departament_id' => 24],
            ['name' => 'Santiago', 'departament_id' => 24],
            ['name' => 'Sibundoy', 'departament_id' => 24],
            ['name' => 'Valle del Guamuez', 'departament_id' => 24],
            ['name' => 'Villagarzón', 'departament_id' => 24],
            ['name' => 'Armenia', 'departament_id' => 25],//Quindío
            ['name' => 'Buenavista', 'departament_id' => 25],
            ['name' => 'Calarcá', 'departament_id' => 25],
            ['name' => 'Circasia', 'departament_id' => 25],
            ['name' => 'Córdoba', 'departament_id' => 25],
            ['name' => 'Filandia', 'departament_id' => 25],
            ['name' => 'Génova', 'departament_id' => 25],
            ['name' => 'La Tebaida', 'departament_id' => 25],
            ['name' => 'Montenegro', 'departament_id' => 25],
            ['name' => 'Pijao', 'departament_id' => 25],
            ['name' => 'Quimbaya', 'departament_id' => 25],
            ['name' => 'Salento', 'departament_id' => 25],
            ['name' => 'Apía', 'departament_id' => 26],//Risaralda
            ['name' => 'Balboa', 'departament_id' => 26],
            ['name' => 'Belén de Umbría', 'departament_id' => 26],
            ['name' => 'Dosquebradas', 'departament_id' => 26],
            ['name' => 'Guática', 'departament_id' => 26],
            ['name' => 'La Celia', 'departament_id' => 26],
            ['name' => 'La Virginia', 'departament_id' => 26],
            ['name' => 'Marsella', 'departament_id' => 26],
            ['name' => 'Mistrató', 'departament_id' => 26],
            ['name' => 'Pereira', 'departament_id' => 26],
            ['name' => 'Pueblo Rico', 'departament_id' => 26],
            ['name' => 'Quinchía', 'departament_id' => 26],
            ['name' => 'Santa Rosa de Cabal', 'departament_id' => 26],
            ['name' => 'Santuario', 'departament_id' => 26],
            ['name' => 'San Andres', 'departament_id' => 27],//San Andres y Providencia
            ['name' => 'Providencia y Santa Catalina', 'departament_id' => 27],
            ['name' => 'Aguada', 'departament_id' => 28],//Santander
            ['name' => 'Albania', 'departament_id' => 28],
            ['name' => 'Aratoca', 'departament_id' => 28],
            ['name' => 'Barbosa', 'departament_id' => 28],
            ['name' => 'Barichara', 'departament_id' => 28],
            ['name' => 'Barrancabermeja', 'departament_id' => 28],
            ['name' => 'Betulia', 'departament_id' => 28],
            ['name' => 'Bolívar', 'departament_id' => 28],
            ['name' => 'Bucaramanga', 'departament_id' => 28],
            ['name' => 'Cabrera', 'departament_id' => 28],
            ['name' => 'California', 'departament_id' => 28],
            ['name' => 'Capitanejo', 'departament_id' => 28],
            ['name' => 'Carcasí', 'departament_id' => 28],
            ['name' => 'Cepitá', 'departament_id' => 28],
            ['name' => 'Cerrito', 'departament_id' => 28],
            ['name' => 'Charalá', 'departament_id' => 28],
            ['name' => 'Charta', 'departament_id' => 28],
            ['name' => 'Chima', 'departament_id' => 28],
            ['name' => 'Chipatá', 'departament_id' => 28],
            ['name' => 'Cimitarra', 'departament_id' => 28],
            ['name' => 'Concepción', 'departament_id' => 28],
            ['name' => 'Confines', 'departament_id' => 28],
            ['name' => 'Contratación', 'departament_id' => 28],
            ['name' => 'Coromoro', 'departament_id' => 28],
            ['name' => 'Curití', 'departament_id' => 28],
            ['name' => 'El Carmen de Chucurí', 'departament_id' => 28],
            ['name' => 'El Guacamayo', 'departament_id' => 28],
            ['name' => 'El Peñón', 'departament_id' => 28],
            ['name' => 'El Playón', 'departament_id' => 28],
            ['name' => 'Encino', 'departament_id' => 28],
            ['name' => 'Enciso', 'departament_id' => 28],
            ['name' => 'Florián', 'departament_id' => 28],
            ['name' => 'Floridablanca', 'departament_id' => 28],
            ['name' => 'Galán', 'departament_id' => 28],
            ['name' => 'Gámbita', 'departament_id' => 28],
            ['name' => 'Girón', 'departament_id' => 28],
            ['name' => 'Guaca', 'departament_id' => 28],
            ['name' => 'Guadalupe', 'departament_id' => 28],
            ['name' => 'Guapotá', 'departament_id' => 28],
            ['name' => 'Guavatá', 'departament_id' => 28],
            ['name' => 'Güepsa', 'departament_id' => 28],
            ['name' => 'Hato', 'departament_id' => 28],
            ['name' => 'Jesús María', 'departament_id' => 28],
            ['name' => 'Jordán', 'departament_id' => 28],
            ['name' => 'La Belleza', 'departament_id' => 28],
            ['name' => 'La Paz', 'departament_id' => 28],
            ['name' => 'Landázuri', 'departament_id' => 28],
            ['name' => 'Lebrija', 'departament_id' => 28],
            ['name' => 'Los Santos', 'departament_id' => 28],
            ['name' => 'Macaravita', 'departament_id' => 28],
            ['name' => 'Málaga', 'departament_id' => 28],
            ['name' => 'Matanza', 'departament_id' => 28],
            ['name' => 'Mogotes', 'departament_id' => 28],
            ['name' => 'Molagavita', 'departament_id' => 28],
            ['name' => 'Ocamonte', 'departament_id' => 28],
            ['name' => 'Oiba', 'departament_id' => 28],
            ['name' => 'Onzaga', 'departament_id' => 28],
            ['name' => 'Palmar', 'departament_id' => 28],
            ['name' => 'Palmas del Socorro', 'departament_id' => 28],
            ['name' => 'Páramo', 'departament_id' => 28],
            ['name' => 'Piedecuesta', 'departament_id' => 28],
            ['name' => 'Pinchote', 'departament_id' => 28],
            ['name' => 'Puente Nacional', 'departament_id' => 28],
            ['name' => 'Puerto Parra', 'departament_id' => 28],
            ['name' => 'Puerto Wilches', 'departament_id' => 28],
            ['name' => 'Rionegro', 'departament_id' => 28],
            ['name' => 'Sabana de Torres', 'departament_id' => 28],
            ['name' => 'San Andrés', 'departament_id' => 28],
            ['name' => 'San Benito', 'departament_id' => 28],
            ['name' => 'San Gil', 'departament_id' => 28],
            ['name' => 'San Joaquín', 'departament_id' => 28],
            ['name' => 'San José de Miranda', 'departament_id' => 28],
            ['name' => 'San Miguel', 'departament_id' => 28],
            ['name' => 'San Vicente de Chucurí', 'departament_id' => 28],
            ['name' => 'Santa Bárbara', 'departament_id' => 28],
            ['name' => 'Santa Helena del Opón', 'departament_id' => 28],
            ['name' => 'Simacota', 'departament_id' => 28],
            ['name' => 'Socorro', 'departament_id' => 28],
            ['name' => 'Suaita', 'departament_id' => 28],
            ['name' => 'Sucre', 'departament_id' => 28],
            ['name' => 'Suratá', 'departament_id' => 28],
            ['name' => 'Tona', 'departament_id' => 28],
            ['name' => 'Valle de San José', 'departament_id' => 28],
            ['name' => 'Vélez', 'departament_id' => 28],
            ['name' => 'Vetas', 'departament_id' => 28],
            ['name' => 'Villanueva', 'departament_id' => 28],
            ['name' => 'Zapatoca', 'departament_id' => 28],
            ['name' => 'Guaranda', 'departament_id' => 29],//Sucre
            ['name' => 'Majagual', 'departament_id' => 29],
            ['name' => 'Sucre', 'departament_id' => 29],
            ['name' => 'Chalán', 'departament_id' => 29],
            ['name' => 'Colosó', 'departament_id' => 29],
            ['name' => 'Morroa', 'departament_id' => 29],
            ['name' => 'Ovejas', 'departament_id' => 29],
            ['name' => 'Sincelejo', 'departament_id' => 29],
            ['name' => 'Coveñas', 'departament_id' => 29],
            ['name' => 'Palmito', 'departament_id' => 29],
            ['name' => 'San Onofre', 'departament_id' => 29],
            ['name' => 'Santiago de Tolú', 'departament_id' => 29],
            ['name' => 'Tolú Viejo', 'departament_id' => 29],
            ['name' => 'Buenavista', 'departament_id' => 29],
            ['name' => 'Corozal', 'departament_id' => 29],
            ['name' => 'El Roble', 'departament_id' => 29],
            ['name' => 'Galeras', 'departament_id' => 29],
            ['name' => 'Los Palmitos', 'departament_id' => 29],
            ['name' => 'Sampués', 'departament_id' => 29],
            ['name' => 'San Juan de Betulia', 'departament_id' => 29],
            ['name' => 'San Pedro', 'departament_id' => 29],
            ['name' => 'Sincé', 'departament_id' => 29],
            ['name' => 'Caimito', 'departament_id' => 29],
            ['name' => 'La Unión', 'departament_id' => 29],
            ['name' => 'San Benito Abad', 'departament_id' => 29],
            ['name' => 'San Luis de Sincé', 'departament_id' => 29],
            ['name' => 'San Marcos', 'departament_id' => 29],
            ['name' => 'Alvarado', 'departament_id' => 30],//Tolima
            ['name' => 'Anzoátegui', 'departament_id' => 30],
            ['name' => 'Cajamarca', 'departament_id' => 30],
            ['name' => 'Coello', 'departament_id' => 30],
            ['name' => 'Espinal', 'departament_id' => 30],
            ['name' => 'Flandes', 'departament_id' => 30],
            ['name' => 'Ibagué', 'departament_id' => 30],
            ['name' => 'Piedras', 'departament_id' => 30],
            ['name' => 'Rovira', 'departament_id' => 30],
            ['name' => 'San Luis', 'departament_id' => 30],
            ['name' => 'Valle de San Juan', 'departament_id' => 30],
            ['name' => 'Casabianca', 'departament_id' => 30],
            ['name' => 'Herveo', 'departament_id' => 30],
            ['name' => 'Lérida', 'departament_id' => 30],
            ['name' => 'Líbano', 'departament_id' => 30],
            ['name' => 'Murillo', 'departament_id' => 30],
            ['name' => 'Santa Isabel', 'departament_id' => 30],
            ['name' => 'Venadillo', 'departament_id' => 30],
            ['name' => 'Villahermosa', 'departament_id' => 30],
            ['name' => 'Ambalema', 'departament_id' => 30],
            ['name' => 'Armero', 'departament_id' => 30],
            ['name' => 'Falan', 'departament_id' => 30],
            ['name' => 'Fresno', 'departament_id' => 30],
            ['name' => 'Honda', 'departament_id' => 30],
            ['name' => 'Mariquita', 'departament_id' => 30],
            ['name' => 'Palocabildo', 'departament_id' => 30],
            ['name' => 'Carmen de Apicalá', 'departament_id' => 30],
            ['name' => 'Cunday', 'departament_id' => 30],
            ['name' => 'Icononzo', 'departament_id' => 30],
            ['name' => 'Melgar', 'departament_id' => 30],
            ['name' => 'Villarrica', 'departament_id' => 30],
            ['name' => 'Ataco', 'departament_id' => 30],
            ['name' => 'Chaparral', 'departament_id' => 30],
            ['name' => 'Coyaima', 'departament_id' => 30],
            ['name' => 'Natagaima', 'departament_id' => 30],
            ['name' => 'Ortega', 'departament_id' => 30],
            ['name' => 'Planadas', 'departament_id' => 30],
            ['name' => 'Rioblanco', 'departament_id' => 30],
            ['name' => 'Roncesvalles', 'departament_id' => 30],
            ['name' => 'San Antonio', 'departament_id' => 30],
            ['name' => 'Alpujarra', 'departament_id' => 30],
            ['name' => 'Dolores', 'departament_id' => 30],
            ['name' => 'Guamo', 'departament_id' => 30],
            ['name' => 'Prado', 'departament_id' => 30],
            ['name' => 'Purificación', 'departament_id' => 30],
            ['name' => 'Saldaña', 'departament_id' => 30],
            ['name' => 'Suárez', 'departament_id' => 30],
            ['name' => 'Albán', 'departament_id' => 31],//Valle del Cauca
            ['name' => 'Alcalá', 'departament_id' => 31],
            ['name' => 'Andalucía', 'departament_id' => 31],
            ['name' => 'Ansermanuevo', 'departament_id' => 31],
            ['name' => 'Argelia', 'departament_id' => 31],
            ['name' => 'Barragán', 'departament_id' => 31],
            ['name' => 'Bitaco', 'departament_id' => 31],
            ['name' => 'Bolívar', 'departament_id' => 31],
            ['name' => 'Buenaventura', 'departament_id' => 31],
            ['name' => 'Buenos Aires', 'departament_id' => 31],
            ['name' => 'Buga', 'departament_id' => 31],
            ['name' => 'Bugalagrande', 'departament_id' => 31],
            ['name' => 'Caicedonia', 'departament_id' => 31],
            ['name' => 'Cali', 'departament_id' => 31],
            ['name' => 'Calima', 'departament_id' => 31],
            ['name' => 'Candelaria', 'departament_id' => 31],
            ['name' => 'Cartago', 'departament_id' => 31],
            ['name' => 'Ceylan', 'departament_id' => 31],
            ['name' => 'Costa Rica', 'departament_id' => 31],
            ['name' => 'Dagua', 'departament_id' => 31],
            ['name' => 'Dapa', 'departament_id' => 31],
            ['name' => 'Darién', 'departament_id' => 31],
            ['name' => 'El Aguila', 'departament_id' => 31],
            ['name' => 'El Bolo', 'departament_id' => 31],
            ['name' => 'El Cairo', 'departament_id' => 31],
            ['name' => 'El Carmelo', 'departament_id' => 31],
            ['name' => 'El Carmen', 'departament_id' => 31],
            ['name' => 'El Cerrito', 'departament_id' => 31],
            ['name' => 'El Dovio', 'departament_id' => 31],
            ['name' => 'Fenicia', 'departament_id' => 31],
            ['name' => 'Florida', 'departament_id' => 31],
            ['name' => 'Galicia', 'departament_id' => 31],
            ['name' => 'Ginebra', 'departament_id' => 31],
            ['name' => 'Guacarí', 'departament_id' => 31],
            ['name' => 'Guadalajara de Buga', 'departament_id' => 31],
            ['name' => 'Jamundí', 'departament_id' => 31],
            ['name' => 'Juachaco', 'departament_id' => 31],
            ['name' => 'La Bocana', 'departament_id' => 31],
            ['name' => 'La Buitrera', 'departament_id' => 31],
            ['name' => 'La Cumbre', 'departament_id' => 31],
            ['name' => 'La Dolores', 'departament_id' => 31],
            ['name' => 'La Iberia', 'departament_id' => 31],
            ['name' => 'La Nubia', 'departament_id' => 31],
            ['name' => 'La Unión', 'departament_id' => 31],
            ['name' => 'La Victoria', 'departament_id' => 31],
            ['name' => 'Ladrilleros', 'departament_id' => 31],
            ['name' => 'Lago Calima', 'departament_id' => 31],
            ['name' => 'Madrigal', 'departament_id' => 31],
            ['name' => 'Obando', 'departament_id' => 31],
            ['name' => 'Palmaseca', 'departament_id' => 31],
            ['name' => 'Palmira', 'departament_id' => 31],
            ['name' => 'Pavas', 'departament_id' => 31],
            ['name' => 'Poblado Campestre', 'departament_id' => 31],
            ['name' => 'Potrerito', 'departament_id' => 31],
            ['name' => 'Pradera', 'departament_id' => 31],
            ['name' => 'Queremal', 'departament_id' => 31],
            ['name' => 'Restrepo', 'departament_id' => 31],
            ['name' => 'Riofrío', 'departament_id' => 31],
            ['name' => 'Roldanillo', 'departament_id' => 31],
            ['name' => 'Rozo', 'departament_id' => 31],
            ['name' => 'Salónica', 'departament_id' => 31],
            ['name' => 'Samaria', 'departament_id' => 31],
            ['name' => 'San Antonio de los Caballeros', 'departament_id' => 31],
            ['name' => 'San Pedro', 'departament_id' => 31],
            ['name' => 'Santa Helena', 'departament_id' => 31],
            ['name' => 'Santa Lucía', 'departament_id' => 31],
            ['name' => 'Sevilla', 'departament_id' => 31],
            ['name' => 'Sonso', 'departament_id' => 31],
            ['name' => 'Tienda Nueva', 'departament_id' => 31],
            ['name' => 'Toro', 'departament_id' => 31],
            ['name' => 'Trujillo', 'departament_id' => 31],
            ['name' => 'Tuluá', 'departament_id' => 31],
            ['name' => 'Ulloa', 'departament_id' => 31],
            ['name' => 'Venecia', 'departament_id' => 31],
            ['name' => 'Versalles', 'departament_id' => 31],
            ['name' => 'Vijes', 'departament_id' => 31],
            ['name' => 'Villagorgona', 'departament_id' => 31],
            ['name' => 'Yotoco', 'departament_id' => 31],
            ['name' => 'Yumbo', 'departament_id' => 31],
            ['name' => 'Zarzal', 'departament_id' => 31],
            ['name' => 'Ameime El Placer', 'departament_id' => 31],
            ['name' => 'Quebrada Nueva', 'departament_id' => 31],
            ['name' => 'Rurales Valle', 'departament_id' => 31],
            ['name' => 'La Marina', 'departament_id' => 31],
            ['name' => 'La Horqueta', 'departament_id' => 31],
            ['name' => 'Bahía Malaga', 'departament_id' => 31],
            ['name' => 'Carurú', 'departament_id' => 32],//Vaupés
            ['name' => 'Mitú', 'departament_id' => 32],
            ['name' => 'Pacoa', 'departament_id' => 32],
            ['name' => 'Papunaua', 'departament_id' => 32],
            ['name' => 'Taraira', 'departament_id' => 32],
            ['name' => 'Yavaraté', 'departament_id' => 32],
            ['name' => 'Cumaribo', 'departament_id' => 33],//Vichada
            ['name' => 'La Primavera', 'departament_id' => 33],
            ['name' => 'Puerto Carreño', 'departament_id' => 33],
            ['name' => 'Santa Rosalía', 'departament_id' => 33]
        ];
        CvMunicipality::insert($city);
    }

}
